name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update file
        run: |
          echo "Last updated: $(date)" >> update.log

      - name: Commit changes
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your@email.com"
          git add .
          git commit -m "Daily update: $(date)" || echo "Nothing to commit"
          git push
