name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with PAT
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Git
        run: |
          git config --global user.name "karman07"
          git config --global user.email "karamnsingharora01@gmail.com"

      - name: Debug:Print
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "$TOKEN" | base64

      - name: Update file
        run: |
          echo "Last updated: $(date)" >> update.log

      - name: Commit and Push changes
        run: |
          git add .
          git commit -m "Daily update: $(date)" || echo "Nothing to commit"
          git push
